// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech/greco3/codecs/audio_decoder_stream_params.proto

package greco;

public final class AudioDecoderStreamParamsOuterClass {
  private AudioDecoderStreamParamsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.id);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AudioDecoderStreamParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:greco.AudioDecoderStreamParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool use_preamble = 1;</code>
     * @return Whether the usePreamble field is set.
     */
    boolean hasUsePreamble();
    /**
     * <code>optional bool use_preamble = 1;</code>
     * @return The usePreamble.
     */
    boolean getUsePreamble();

    /**
     * <code>optional bool tagged_channels = 2;</code>
     * @return Whether the taggedChannels field is set.
     */
    boolean hasTaggedChannels();
    /**
     * <code>optional bool tagged_channels = 2;</code>
     * @return The taggedChannels.
     */
    boolean getTaggedChannels();
  }
  /**
   * Protobuf type {@code greco.AudioDecoderStreamParams}
   */
  public static final class AudioDecoderStreamParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:greco.AudioDecoderStreamParams)
      AudioDecoderStreamParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AudioDecoderStreamParams.newBuilder() to construct.
    private AudioDecoderStreamParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AudioDecoderStreamParams() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AudioDecoderStreamParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return greco.AudioDecoderStreamParamsOuterClass.internal_static_greco_AudioDecoderStreamParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return greco.AudioDecoderStreamParamsOuterClass.internal_static_greco_AudioDecoderStreamParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.class, greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.Builder.class);
    }

    private int bitField0_;
    public static final int USE_PREAMBLE_FIELD_NUMBER = 1;
    private boolean usePreamble_;
    /**
     * <code>optional bool use_preamble = 1;</code>
     * @return Whether the usePreamble field is set.
     */
    @java.lang.Override
    public boolean hasUsePreamble() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool use_preamble = 1;</code>
     * @return The usePreamble.
     */
    @java.lang.Override
    public boolean getUsePreamble() {
      return usePreamble_;
    }

    public static final int TAGGED_CHANNELS_FIELD_NUMBER = 2;
    private boolean taggedChannels_;
    /**
     * <code>optional bool tagged_channels = 2;</code>
     * @return Whether the taggedChannels field is set.
     */
    @java.lang.Override
    public boolean hasTaggedChannels() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool tagged_channels = 2;</code>
     * @return The taggedChannels.
     */
    @java.lang.Override
    public boolean getTaggedChannels() {
      return taggedChannels_;
    }

    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code greco.AudioDecoderStreamParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:greco.AudioDecoderStreamParams)
        greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return greco.AudioDecoderStreamParamsOuterClass.internal_static_greco_AudioDecoderStreamParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return greco.AudioDecoderStreamParamsOuterClass.internal_static_greco_AudioDecoderStreamParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.class, greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.Builder.class);
      }

      // Construct using greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        usePreamble_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        taggedChannels_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return greco.AudioDecoderStreamParamsOuterClass.internal_static_greco_AudioDecoderStreamParams_descriptor;
      }

      @java.lang.Override
      public greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams getDefaultInstanceForType() {
        return greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.getDefaultInstance();
      }

      @java.lang.Override
      public greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams build() {
        greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams buildPartial() {
        greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams result = new greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.usePreamble_ = usePreamble_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.taggedChannels_ = taggedChannels_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private boolean usePreamble_ ;
      /**
       * <code>optional bool use_preamble = 1;</code>
       * @return Whether the usePreamble field is set.
       */
      @java.lang.Override
      public boolean hasUsePreamble() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool use_preamble = 1;</code>
       * @return The usePreamble.
       */
      @java.lang.Override
      public boolean getUsePreamble() {
        return usePreamble_;
      }
      /**
       * <code>optional bool use_preamble = 1;</code>
       * @param value The usePreamble to set.
       * @return This builder for chaining.
       */
      public Builder setUsePreamble(boolean value) {
        bitField0_ |= 0x00000001;
        usePreamble_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool use_preamble = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsePreamble() {
        bitField0_ = (bitField0_ & ~0x00000001);
        usePreamble_ = false;
        onChanged();
        return this;
      }

      private boolean taggedChannels_ ;
      /**
       * <code>optional bool tagged_channels = 2;</code>
       * @return Whether the taggedChannels field is set.
       */
      @java.lang.Override
      public boolean hasTaggedChannels() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bool tagged_channels = 2;</code>
       * @return The taggedChannels.
       */
      @java.lang.Override
      public boolean getTaggedChannels() {
        return taggedChannels_;
      }
      /**
       * <code>optional bool tagged_channels = 2;</code>
       * @param value The taggedChannels to set.
       * @return This builder for chaining.
       */
      public Builder setTaggedChannels(boolean value) {
        bitField0_ |= 0x00000002;
        taggedChannels_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool tagged_channels = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaggedChannels() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taggedChannels_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:greco.AudioDecoderStreamParams)
    }

    // @@protoc_insertion_point(class_scope:greco.AudioDecoderStreamParams)
    private static final greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams();
    }

    public static greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AudioDecoderStreamParams>
        PARSER = new com.google.protobuf.AbstractParser<AudioDecoderStreamParams>() {
      @java.lang.Override
      public AudioDecoderStreamParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AudioDecoderStreamParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AudioDecoderStreamParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int ID_FIELD_NUMBER = 82257718;
    /**
     * <code>extend .greco.Params { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        greco.ParamsProto.Params,
        greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams> id = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.getDefaultInstance(),
          0,
          greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.class,
          greco.AudioDecoderStreamParamsOuterClass.AudioDecoderStreamParams.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greco_AudioDecoderStreamParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greco_AudioDecoderStreamParams_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6speech/greco3/codecs/audio_decoder_str" +
      "eam_params.proto\022\005greco\032\037speech/greco3/c" +
      "ore/params.proto\"\210\001\n\030AudioDecoderStreamP" +
      "arams\022\024\n\014use_preamble\030\001 \001(\010\022\027\n\017tagged_ch" +
      "annels\030\002 \001(\0102=\n\002id\022\r.greco.Params\030\266\316\234\' \001" +
      "(\0132\037.greco.AudioDecoderStreamParamsB\010H\002\242" +
      "\002\003GRC"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          greco.ParamsProto.getDescriptor(),
        });
    internal_static_greco_AudioDecoderStreamParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_greco_AudioDecoderStreamParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greco_AudioDecoderStreamParams_descriptor,
        new java.lang.String[] { "UsePreamble", "TaggedChannels", });
    greco.ParamsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
