// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech/greco3/decoder_endpointer/decoder_endpointer_model_feature_builder_params.proto

package greco;

public final class DecoderEndpointerModelFeatureBuilderParamsOuterClass {
  private DecoderEndpointerModelFeatureBuilderParamsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DecoderEndpointerModelFeatureBuilderParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:greco.DecoderEndpointerModelFeatureBuilderParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
     * @return A list containing the features.
     */
    java.util.List<greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature> getFeaturesList();
    /**
     * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
     * @return The count of features.
     */
    int getFeaturesCount();
    /**
     * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
     * @param index The index of the element to return.
     * @return The features at the given index.
     */
    greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature getFeatures(int index);

    /**
     * <code>repeated int32 phones_rate_interval_ms = 2;</code>
     * @return A list containing the phonesRateIntervalMs.
     */
    java.util.List<java.lang.Integer> getPhonesRateIntervalMsList();
    /**
     * <code>repeated int32 phones_rate_interval_ms = 2;</code>
     * @return The count of phonesRateIntervalMs.
     */
    int getPhonesRateIntervalMsCount();
    /**
     * <code>repeated int32 phones_rate_interval_ms = 2;</code>
     * @param index The index of the element to return.
     * @return The phonesRateIntervalMs at the given index.
     */
    int getPhonesRateIntervalMs(int index);
  }
  /**
   * Protobuf type {@code greco.DecoderEndpointerModelFeatureBuilderParams}
   */
  public static final class DecoderEndpointerModelFeatureBuilderParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:greco.DecoderEndpointerModelFeatureBuilderParams)
      DecoderEndpointerModelFeatureBuilderParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DecoderEndpointerModelFeatureBuilderParams.newBuilder() to construct.
    private DecoderEndpointerModelFeatureBuilderParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DecoderEndpointerModelFeatureBuilderParams() {
      features_ = java.util.Collections.emptyList();
      phonesRateIntervalMs_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DecoderEndpointerModelFeatureBuilderParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.class, greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Builder.class);
    }

    /**
     * Protobuf enum {@code greco.DecoderEndpointerModelFeatureBuilderParams.Feature}
     */
    public enum Feature
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ACOUSTICS = 1;</code>
       */
      ACOUSTICS(1),
      /**
       * <code>SENTENCE_END_COST = 2;</code>
       */
      SENTENCE_END_COST(2),
      /**
       * <code>LAST_PHONE_TO_END_SEC = 3;</code>
       */
      LAST_PHONE_TO_END_SEC(3),
      /**
       * <code>CONTAINS_SPEECH = 4;</code>
       */
      CONTAINS_SPEECH(4),
      /**
       * <code>PHONES_RATE_OVER_1SEC = 5;</code>
       */
      PHONES_RATE_OVER_1SEC(5),
      /**
       * <code>PHONES_RATE_OVER_2SEC = 6;</code>
       */
      PHONES_RATE_OVER_2SEC(6),
      /**
       * <code>DECODER_LATENCY_SEC = 7;</code>
       */
      DECODER_LATENCY_SEC(7),
      /**
       * <code>PHONES_RATE = 8;</code>
       */
      PHONES_RATE(8),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ACOUSTICS = 1;</code>
       */
      public static final int ACOUSTICS_VALUE = 1;
      /**
       * <code>SENTENCE_END_COST = 2;</code>
       */
      public static final int SENTENCE_END_COST_VALUE = 2;
      /**
       * <code>LAST_PHONE_TO_END_SEC = 3;</code>
       */
      public static final int LAST_PHONE_TO_END_SEC_VALUE = 3;
      /**
       * <code>CONTAINS_SPEECH = 4;</code>
       */
      public static final int CONTAINS_SPEECH_VALUE = 4;
      /**
       * <code>PHONES_RATE_OVER_1SEC = 5;</code>
       */
      public static final int PHONES_RATE_OVER_1SEC_VALUE = 5;
      /**
       * <code>PHONES_RATE_OVER_2SEC = 6;</code>
       */
      public static final int PHONES_RATE_OVER_2SEC_VALUE = 6;
      /**
       * <code>DECODER_LATENCY_SEC = 7;</code>
       */
      public static final int DECODER_LATENCY_SEC_VALUE = 7;
      /**
       * <code>PHONES_RATE = 8;</code>
       */
      public static final int PHONES_RATE_VALUE = 8;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Feature valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Feature forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return ACOUSTICS;
          case 2: return SENTENCE_END_COST;
          case 3: return LAST_PHONE_TO_END_SEC;
          case 4: return CONTAINS_SPEECH;
          case 5: return PHONES_RATE_OVER_1SEC;
          case 6: return PHONES_RATE_OVER_2SEC;
          case 7: return DECODER_LATENCY_SEC;
          case 8: return PHONES_RATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Feature>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Feature> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Feature>() {
              public Feature findValueByNumber(int number) {
                return Feature.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.getDescriptor().getEnumTypes().get(0);
      }

      private static final Feature[] VALUES = values();

      public static Feature valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Feature(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:greco.DecoderEndpointerModelFeatureBuilderParams.Feature)
    }

    public static final int FEATURES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> features_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature> features_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature>() {
              public greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature convert(java.lang.Integer from) {
                @SuppressWarnings("deprecation")
                greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature result = greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature.valueOf(from);
                return result == null ? greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature.UNKNOWN : result;
              }
            };
    /**
     * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
     * @return A list containing the features.
     */
    @java.lang.Override
    public java.util.List<greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature> getFeaturesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature>(features_, features_converter_);
    }
    /**
     * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
     * @return The count of features.
     */
    @java.lang.Override
    public int getFeaturesCount() {
      return features_.size();
    }
    /**
     * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
     * @param index The index of the element to return.
     * @return The features at the given index.
     */
    @java.lang.Override
    public greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature getFeatures(int index) {
      return features_converter_.convert(features_.get(index));
    }

    public static final int PHONES_RATE_INTERVAL_MS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList phonesRateIntervalMs_;
    /**
     * <code>repeated int32 phones_rate_interval_ms = 2;</code>
     * @return A list containing the phonesRateIntervalMs.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getPhonesRateIntervalMsList() {
      return phonesRateIntervalMs_;
    }
    /**
     * <code>repeated int32 phones_rate_interval_ms = 2;</code>
     * @return The count of phonesRateIntervalMs.
     */
    public int getPhonesRateIntervalMsCount() {
      return phonesRateIntervalMs_.size();
    }
    /**
     * <code>repeated int32 phones_rate_interval_ms = 2;</code>
     * @param index The index of the element to return.
     * @return The phonesRateIntervalMs at the given index.
     */
    public int getPhonesRateIntervalMs(int index) {
      return phonesRateIntervalMs_.getInt(index);
    }

    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code greco.DecoderEndpointerModelFeatureBuilderParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:greco.DecoderEndpointerModelFeatureBuilderParams)
        greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.class, greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Builder.class);
      }

      // Construct using greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        features_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        phonesRateIntervalMs_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_descriptor;
      }

      @java.lang.Override
      public greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams getDefaultInstanceForType() {
        return greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.getDefaultInstance();
      }

      @java.lang.Override
      public greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams build() {
        greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams buildPartial() {
        greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams result = new greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          features_ = java.util.Collections.unmodifiableList(features_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.features_ = features_;
        if (((bitField0_ & 0x00000002) != 0)) {
          phonesRateIntervalMs_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.phonesRateIntervalMs_ = phonesRateIntervalMs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> features_ =
        java.util.Collections.emptyList();
      private void ensureFeaturesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          features_ = new java.util.ArrayList<java.lang.Integer>(features_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
       * @return A list containing the features.
       */
      public java.util.List<greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature> getFeaturesList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature>(features_, features_converter_);
      }
      /**
       * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
       * @return The count of features.
       */
      public int getFeaturesCount() {
        return features_.size();
      }
      /**
       * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
       * @param index The index of the element to return.
       * @return The features at the given index.
       */
      public greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature getFeatures(int index) {
        return features_converter_.convert(features_.get(index));
      }
      /**
       * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
       * @param index The index to set the value at.
       * @param value The features to set.
       * @return This builder for chaining.
       */
      public Builder setFeatures(
          int index, greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturesIsMutable();
        features_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
       * @param value The features to add.
       * @return This builder for chaining.
       */
      public Builder addFeatures(greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturesIsMutable();
        features_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
       * @param values The features to add.
       * @return This builder for chaining.
       */
      public Builder addAllFeatures(
          java.lang.Iterable<? extends greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature> values) {
        ensureFeaturesIsMutable();
        for (greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams.Feature value : values) {
          features_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .greco.DecoderEndpointerModelFeatureBuilderParams.Feature features = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeatures() {
        features_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList phonesRateIntervalMs_ = emptyIntList();
      private void ensurePhonesRateIntervalMsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          phonesRateIntervalMs_ = mutableCopy(phonesRateIntervalMs_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 phones_rate_interval_ms = 2;</code>
       * @return A list containing the phonesRateIntervalMs.
       */
      public java.util.List<java.lang.Integer>
          getPhonesRateIntervalMsList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(phonesRateIntervalMs_) : phonesRateIntervalMs_;
      }
      /**
       * <code>repeated int32 phones_rate_interval_ms = 2;</code>
       * @return The count of phonesRateIntervalMs.
       */
      public int getPhonesRateIntervalMsCount() {
        return phonesRateIntervalMs_.size();
      }
      /**
       * <code>repeated int32 phones_rate_interval_ms = 2;</code>
       * @param index The index of the element to return.
       * @return The phonesRateIntervalMs at the given index.
       */
      public int getPhonesRateIntervalMs(int index) {
        return phonesRateIntervalMs_.getInt(index);
      }
      /**
       * <code>repeated int32 phones_rate_interval_ms = 2;</code>
       * @param index The index to set the value at.
       * @param value The phonesRateIntervalMs to set.
       * @return This builder for chaining.
       */
      public Builder setPhonesRateIntervalMs(
          int index, int value) {
        ensurePhonesRateIntervalMsIsMutable();
        phonesRateIntervalMs_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 phones_rate_interval_ms = 2;</code>
       * @param value The phonesRateIntervalMs to add.
       * @return This builder for chaining.
       */
      public Builder addPhonesRateIntervalMs(int value) {
        ensurePhonesRateIntervalMsIsMutable();
        phonesRateIntervalMs_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 phones_rate_interval_ms = 2;</code>
       * @param values The phonesRateIntervalMs to add.
       * @return This builder for chaining.
       */
      public Builder addAllPhonesRateIntervalMs(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePhonesRateIntervalMsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phonesRateIntervalMs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 phones_rate_interval_ms = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhonesRateIntervalMs() {
        phonesRateIntervalMs_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:greco.DecoderEndpointerModelFeatureBuilderParams)
    }

    // @@protoc_insertion_point(class_scope:greco.DecoderEndpointerModelFeatureBuilderParams)
    private static final greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams();
    }

    public static greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DecoderEndpointerModelFeatureBuilderParams>
        PARSER = new com.google.protobuf.AbstractParser<DecoderEndpointerModelFeatureBuilderParams>() {
      @java.lang.Override
      public DecoderEndpointerModelFeatureBuilderParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DecoderEndpointerModelFeatureBuilderParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DecoderEndpointerModelFeatureBuilderParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public greco.DecoderEndpointerModelFeatureBuilderParamsOuterClass.DecoderEndpointerModelFeatureBuilderParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nVspeech/greco3/decoder_endpointer/decod" +
      "er_endpointer_model_feature_builder_para" +
      "ms.proto\022\005greco\"\351\002\n*DecoderEndpointerMod" +
      "elFeatureBuilderParams\022K\n\010features\030\001 \003(\016" +
      "29.greco.DecoderEndpointerModelFeatureBu" +
      "ilderParams.Feature\022\037\n\027phones_rate_inter" +
      "val_ms\030\002 \003(\005\"\314\001\n\007Feature\022\013\n\007UNKNOWN\020\000\022\r\n" +
      "\tACOUSTICS\020\001\022\025\n\021SENTENCE_END_COST\020\002\022\031\n\025L" +
      "AST_PHONE_TO_END_SEC\020\003\022\023\n\017CONTAINS_SPEEC" +
      "H\020\004\022\031\n\025PHONES_RATE_OVER_1SEC\020\005\022\031\n\025PHONES" +
      "_RATE_OVER_2SEC\020\006\022\027\n\023DECODER_LATENCY_SEC" +
      "\020\007\022\017\n\013PHONES_RATE\020\010B\002H\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greco_DecoderEndpointerModelFeatureBuilderParams_descriptor,
        new java.lang.String[] { "Features", "PhonesRateIntervalMs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
