// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech/service/context/features/dialog/dialog-features.proto

package speech.context.features;

public final class DialogFeatures {
  private DialogFeatures() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.spec);
    registry.add(speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.spec);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DialogIntentFeatureGeneratorSpecOrBuilder extends
      // @@protoc_insertion_point(interface_extends:speech.context.features.DialogIntentFeatureGeneratorSpec)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .assistant.api.params.FocusParams.Focus focus = 1;</code>
     * @return Whether the focus field is set.
     */
    boolean hasFocus();
    /**
     * <code>optional .assistant.api.params.FocusParams.Focus focus = 1;</code>
     * @return The focus.
     */
    com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus getFocus();
  }
  /**
   * Protobuf type {@code speech.context.features.DialogIntentFeatureGeneratorSpec}
   */
  public static final class DialogIntentFeatureGeneratorSpec extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:speech.context.features.DialogIntentFeatureGeneratorSpec)
      DialogIntentFeatureGeneratorSpecOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DialogIntentFeatureGeneratorSpec.newBuilder() to construct.
    private DialogIntentFeatureGeneratorSpec(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DialogIntentFeatureGeneratorSpec() {
      focus_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DialogIntentFeatureGeneratorSpec();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.class, speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.Builder.class);
    }

    private int bitField0_;
    public static final int FOCUS_FIELD_NUMBER = 1;
    private int focus_;
    /**
     * <code>optional .assistant.api.params.FocusParams.Focus focus = 1;</code>
     * @return Whether the focus field is set.
     */
    @java.lang.Override public boolean hasFocus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .assistant.api.params.FocusParams.Focus focus = 1;</code>
     * @return The focus.
     */
    @java.lang.Override public com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus getFocus() {
      @SuppressWarnings("deprecation")
      com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus result = com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus.valueOf(focus_);
      return result == null ? com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus.UNKNOWN : result;
    }

    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code speech.context.features.DialogIntentFeatureGeneratorSpec}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:speech.context.features.DialogIntentFeatureGeneratorSpec)
        speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpecOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.class, speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.Builder.class);
      }

      // Construct using speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        focus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_descriptor;
      }

      @java.lang.Override
      public speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec getDefaultInstanceForType() {
        return speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.getDefaultInstance();
      }

      @java.lang.Override
      public speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec build() {
        speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec buildPartial() {
        speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec result = new speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.focus_ = focus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private int focus_ = 0;
      /**
       * <code>optional .assistant.api.params.FocusParams.Focus focus = 1;</code>
       * @return Whether the focus field is set.
       */
      @java.lang.Override public boolean hasFocus() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .assistant.api.params.FocusParams.Focus focus = 1;</code>
       * @return The focus.
       */
      @java.lang.Override
      public com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus getFocus() {
        @SuppressWarnings("deprecation")
        com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus result = com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus.valueOf(focus_);
        return result == null ? com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus.UNKNOWN : result;
      }
      /**
       * <code>optional .assistant.api.params.FocusParams.Focus focus = 1;</code>
       * @param value The focus to set.
       * @return This builder for chaining.
       */
      public Builder setFocus(com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        focus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .assistant.api.params.FocusParams.Focus focus = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFocus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        focus_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:speech.context.features.DialogIntentFeatureGeneratorSpec)
    }

    // @@protoc_insertion_point(class_scope:speech.context.features.DialogIntentFeatureGeneratorSpec)
    private static final speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec();
    }

    public static speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DialogIntentFeatureGeneratorSpec>
        PARSER = new com.google.protobuf.AbstractParser<DialogIntentFeatureGeneratorSpec>() {
      @java.lang.Override
      public DialogIntentFeatureGeneratorSpec parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DialogIntentFeatureGeneratorSpec> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DialogIntentFeatureGeneratorSpec> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int SPEC_FIELD_NUMBER = 273384750;
    /**
     * <code>extend .speech.context.features.FeatureGeneratorSpec { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        speech.context.features.FeatureSchemaOuterClass.FeatureGeneratorSpec,
        speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec> spec = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.getDefaultInstance(),
          0,
          speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.class,
          speech.context.features.DialogFeatures.DialogIntentFeatureGeneratorSpec.getDefaultInstance());
  }

  public interface DialogFieldFeatureGeneratorSpecOrBuilder extends
      // @@protoc_insertion_point(interface_extends:speech.context.features.DialogFieldFeatureGeneratorSpec)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string intent_name = 1;</code>
     * @return Whether the intentName field is set.
     */
    boolean hasIntentName();
    /**
     * <code>optional string intent_name = 1;</code>
     * @return The intentName.
     */
    java.lang.String getIntentName();
    /**
     * <code>optional string intent_name = 1;</code>
     * @return The bytes for intentName.
     */
    com.google.protobuf.ByteString
        getIntentNameBytes();

    /**
     * <code>optional bool concatenate_intent_name = 2;</code>
     * @return Whether the concatenateIntentName field is set.
     */
    boolean hasConcatenateIntentName();
    /**
     * <code>optional bool concatenate_intent_name = 2;</code>
     * @return The concatenateIntentName.
     */
    boolean getConcatenateIntentName();

    /**
     * <code>optional .assistant.api.params.FocusParams.Focus intent_focus = 3;</code>
     * @return Whether the intentFocus field is set.
     */
    boolean hasIntentFocus();
    /**
     * <code>optional .assistant.api.params.FocusParams.Focus intent_focus = 3;</code>
     * @return The intentFocus.
     */
    com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus getIntentFocus();

    /**
     * <code>optional .quality.dialog_manager.IntentStateSignals.FieldStatus status = 4;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>optional .quality.dialog_manager.IntentStateSignals.FieldStatus status = 4;</code>
     * @return The status.
     */
    com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus getStatus();
  }
  /**
   * Protobuf type {@code speech.context.features.DialogFieldFeatureGeneratorSpec}
   */
  public static final class DialogFieldFeatureGeneratorSpec extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:speech.context.features.DialogFieldFeatureGeneratorSpec)
      DialogFieldFeatureGeneratorSpecOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DialogFieldFeatureGeneratorSpec.newBuilder() to construct.
    private DialogFieldFeatureGeneratorSpec(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DialogFieldFeatureGeneratorSpec() {
      intentName_ = "";
      intentFocus_ = 0;
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DialogFieldFeatureGeneratorSpec();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.class, speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.Builder.class);
    }

    private int bitField0_;
    public static final int INTENT_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object intentName_;
    /**
     * <code>optional string intent_name = 1;</code>
     * @return Whether the intentName field is set.
     */
    @java.lang.Override
    public boolean hasIntentName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string intent_name = 1;</code>
     * @return The intentName.
     */
    @java.lang.Override
    public java.lang.String getIntentName() {
      java.lang.Object ref = intentName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          intentName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string intent_name = 1;</code>
     * @return The bytes for intentName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIntentNameBytes() {
      java.lang.Object ref = intentName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        intentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONCATENATE_INTENT_NAME_FIELD_NUMBER = 2;
    private boolean concatenateIntentName_;
    /**
     * <code>optional bool concatenate_intent_name = 2;</code>
     * @return Whether the concatenateIntentName field is set.
     */
    @java.lang.Override
    public boolean hasConcatenateIntentName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool concatenate_intent_name = 2;</code>
     * @return The concatenateIntentName.
     */
    @java.lang.Override
    public boolean getConcatenateIntentName() {
      return concatenateIntentName_;
    }

    public static final int INTENT_FOCUS_FIELD_NUMBER = 3;
    private int intentFocus_;
    /**
     * <code>optional .assistant.api.params.FocusParams.Focus intent_focus = 3;</code>
     * @return Whether the intentFocus field is set.
     */
    @java.lang.Override public boolean hasIntentFocus() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .assistant.api.params.FocusParams.Focus intent_focus = 3;</code>
     * @return The intentFocus.
     */
    @java.lang.Override public com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus getIntentFocus() {
      @SuppressWarnings("deprecation")
      com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus result = com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus.valueOf(intentFocus_);
      return result == null ? com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus.UNKNOWN : result;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>optional .quality.dialog_manager.IntentStateSignals.FieldStatus status = 4;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .quality.dialog_manager.IntentStateSignals.FieldStatus status = 4;</code>
     * @return The status.
     */
    @java.lang.Override public com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus result = com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus.valueOf(status_);
      return result == null ? com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus.UNKNOWN_FIELD_STATUS : result;
    }

    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code speech.context.features.DialogFieldFeatureGeneratorSpec}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:speech.context.features.DialogFieldFeatureGeneratorSpec)
        speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpecOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.class, speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.Builder.class);
      }

      // Construct using speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        intentName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        concatenateIntentName_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        intentFocus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return speech.context.features.DialogFeatures.internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_descriptor;
      }

      @java.lang.Override
      public speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec getDefaultInstanceForType() {
        return speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.getDefaultInstance();
      }

      @java.lang.Override
      public speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec build() {
        speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec buildPartial() {
        speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec result = new speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.intentName_ = intentName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.concatenateIntentName_ = concatenateIntentName_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.intentFocus_ = intentFocus_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private java.lang.Object intentName_ = "";
      /**
       * <code>optional string intent_name = 1;</code>
       * @return Whether the intentName field is set.
       */
      public boolean hasIntentName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string intent_name = 1;</code>
       * @return The intentName.
       */
      public java.lang.String getIntentName() {
        java.lang.Object ref = intentName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            intentName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string intent_name = 1;</code>
       * @return The bytes for intentName.
       */
      public com.google.protobuf.ByteString
          getIntentNameBytes() {
        java.lang.Object ref = intentName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          intentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string intent_name = 1;</code>
       * @param value The intentName to set.
       * @return This builder for chaining.
       */
      public Builder setIntentName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        intentName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string intent_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntentName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        intentName_ = getDefaultInstance().getIntentName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string intent_name = 1;</code>
       * @param value The bytes for intentName to set.
       * @return This builder for chaining.
       */
      public Builder setIntentNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        intentName_ = value;
        onChanged();
        return this;
      }

      private boolean concatenateIntentName_ ;
      /**
       * <code>optional bool concatenate_intent_name = 2;</code>
       * @return Whether the concatenateIntentName field is set.
       */
      @java.lang.Override
      public boolean hasConcatenateIntentName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bool concatenate_intent_name = 2;</code>
       * @return The concatenateIntentName.
       */
      @java.lang.Override
      public boolean getConcatenateIntentName() {
        return concatenateIntentName_;
      }
      /**
       * <code>optional bool concatenate_intent_name = 2;</code>
       * @param value The concatenateIntentName to set.
       * @return This builder for chaining.
       */
      public Builder setConcatenateIntentName(boolean value) {
        bitField0_ |= 0x00000002;
        concatenateIntentName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool concatenate_intent_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConcatenateIntentName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        concatenateIntentName_ = false;
        onChanged();
        return this;
      }

      private int intentFocus_ = 0;
      /**
       * <code>optional .assistant.api.params.FocusParams.Focus intent_focus = 3;</code>
       * @return Whether the intentFocus field is set.
       */
      @java.lang.Override public boolean hasIntentFocus() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .assistant.api.params.FocusParams.Focus intent_focus = 3;</code>
       * @return The intentFocus.
       */
      @java.lang.Override
      public com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus getIntentFocus() {
        @SuppressWarnings("deprecation")
        com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus result = com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus.valueOf(intentFocus_);
        return result == null ? com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus.UNKNOWN : result;
      }
      /**
       * <code>optional .assistant.api.params.FocusParams.Focus intent_focus = 3;</code>
       * @param value The intentFocus to set.
       * @return This builder for chaining.
       */
      public Builder setIntentFocus(com.google.assistant.api.params.proto.FocusParamsProto.FocusParams.Focus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        intentFocus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .assistant.api.params.FocusParams.Focus intent_focus = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntentFocus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        intentFocus_ = 0;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>optional .quality.dialog_manager.IntentStateSignals.FieldStatus status = 4;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .quality.dialog_manager.IntentStateSignals.FieldStatus status = 4;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus getStatus() {
        @SuppressWarnings("deprecation")
        com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus result = com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus.valueOf(status_);
        return result == null ? com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus.UNKNOWN_FIELD_STATUS : result;
      }
      /**
       * <code>optional .quality.dialog_manager.IntentStateSignals.FieldStatus status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.google.dialog.proto.DialogIntentStateProto.IntentStateSignals.FieldStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .quality.dialog_manager.IntentStateSignals.FieldStatus status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:speech.context.features.DialogFieldFeatureGeneratorSpec)
    }

    // @@protoc_insertion_point(class_scope:speech.context.features.DialogFieldFeatureGeneratorSpec)
    private static final speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec();
    }

    public static speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DialogFieldFeatureGeneratorSpec>
        PARSER = new com.google.protobuf.AbstractParser<DialogFieldFeatureGeneratorSpec>() {
      @java.lang.Override
      public DialogFieldFeatureGeneratorSpec parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DialogFieldFeatureGeneratorSpec> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DialogFieldFeatureGeneratorSpec> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int SPEC_FIELD_NUMBER = 273384751;
    /**
     * <code>extend .speech.context.features.FeatureGeneratorSpec { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        speech.context.features.FeatureSchemaOuterClass.FeatureGeneratorSpec,
        speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec> spec = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.getDefaultInstance(),
          0,
          speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.class,
          speech.context.features.DialogFeatures.DialogFieldFeatureGeneratorSpec.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<speech/service/context/features/dialog" +
      "/dialog-features.proto\022\027speech.context.f" +
      "eatures\032\'assistant/api/params/focus_para" +
      "ms.proto\0326quality/dialog_manager/proto/d" +
      "ialog_intent_state.proto\0324speech/service" +
      "/context/features/feature-schema.proto\"\326" +
      "\001\n DialogIntentFeatureGeneratorSpec\0226\n\005f" +
      "ocus\030\001 \001(\0162\'.assistant.api.params.FocusP" +
      "arams.Focus2z\n\004spec\022-.speech.context.fea" +
      "tures.FeatureGeneratorSpec\030\256\212\256\202\001 \001(\01329.s" +
      "peech.context.features.DialogIntentFeatu" +
      "reGeneratorSpec\"\331\002\n\037DialogFieldFeatureGe" +
      "neratorSpec\022\023\n\013intent_name\030\001 \001(\t\022\037\n\027conc" +
      "atenate_intent_name\030\002 \001(\010\022=\n\014intent_focu" +
      "s\030\003 \001(\0162\'.assistant.api.params.FocusPara" +
      "ms.Focus\022F\n\006status\030\004 \001(\01626.quality.dialo" +
      "g_manager.IntentStateSignals.FieldStatus" +
      "2y\n\004spec\022-.speech.context.features.Featu" +
      "reGeneratorSpec\030\257\212\256\202\001 \001(\01328.speech.conte" +
      "xt.features.DialogFieldFeatureGeneratorS" +
      "pecB\002H\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.assistant.api.params.proto.FocusParamsProto.getDescriptor(),
          com.google.dialog.proto.DialogIntentStateProto.getDescriptor(),
          speech.context.features.FeatureSchemaOuterClass.getDescriptor(),
        });
    internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_context_features_DialogIntentFeatureGeneratorSpec_descriptor,
        new java.lang.String[] { "Focus", });
    internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_context_features_DialogFieldFeatureGeneratorSpec_descriptor,
        new java.lang.String[] { "IntentName", "ConcatenateIntentName", "IntentFocus", "Status", });
    com.google.assistant.api.params.proto.FocusParamsProto.getDescriptor();
    com.google.dialog.proto.DialogIntentStateProto.getDescriptor();
    speech.context.features.FeatureSchemaOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
