// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logs/proto/speech/service/timeline_event.proto

package com.google.speech.logs.timeline;

public interface EndpointDelayInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech.logs.timeline.EndpointDelayInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 length_usec = 1;</code>
   * @return Whether the lengthUsec field is set.
   */
  boolean hasLengthUsec();
  /**
   * <code>optional int64 length_usec = 1;</code>
   * @return The lengthUsec.
   */
  long getLengthUsec();
}
