// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech/training_cache/proto/metrics.proto

package com.google.speech.trainingcache;

public interface CleanupCycleSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech.training_cache.CleanupCycleSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 num_events_cached = 1;</code>
   * @return Whether the numEventsCached field is set.
   */
  boolean hasNumEventsCached();
  /**
   * <code>optional int64 num_events_cached = 1;</code>
   * @return The numEventsCached.
   */
  long getNumEventsCached();

  /**
   * <code>optional int64 num_events_deleted = 2;</code>
   * @return Whether the numEventsDeleted field is set.
   */
  boolean hasNumEventsDeleted();
  /**
   * <code>optional int64 num_events_deleted = 2;</code>
   * @return The numEventsDeleted.
   */
  long getNumEventsDeleted();

  /**
   * <code>optional int64 num_bytes_cached = 3;</code>
   * @return Whether the numBytesCached field is set.
   */
  boolean hasNumBytesCached();
  /**
   * <code>optional int64 num_bytes_cached = 3;</code>
   * @return The numBytesCached.
   */
  long getNumBytesCached();

  /**
   * <code>optional int64 num_bytes_deleted = 4;</code>
   * @return Whether the numBytesDeleted field is set.
   */
  boolean hasNumBytesDeleted();
  /**
   * <code>optional int64 num_bytes_deleted = 4;</code>
   * @return The numBytesDeleted.
   */
  long getNumBytesDeleted();

  /**
   * <code>optional int64 num_files_cached = 5;</code>
   * @return Whether the numFilesCached field is set.
   */
  boolean hasNumFilesCached();
  /**
   * <code>optional int64 num_files_cached = 5;</code>
   * @return The numFilesCached.
   */
  long getNumFilesCached();

  /**
   * <code>optional int64 num_files_deleted = 6;</code>
   * @return Whether the numFilesDeleted field is set.
   */
  boolean hasNumFilesDeleted();
  /**
   * <code>optional int64 num_files_deleted = 6;</code>
   * @return The numFilesDeleted.
   */
  long getNumFilesDeleted();

  /**
   * <code>optional .speech.training_cache.Histogram ttl_overdues_sec_histogram = 8;</code>
   * @return Whether the ttlOverduesSecHistogram field is set.
   */
  boolean hasTtlOverduesSecHistogram();
  /**
   * <code>optional .speech.training_cache.Histogram ttl_overdues_sec_histogram = 8;</code>
   * @return The ttlOverduesSecHistogram.
   */
  com.google.speech.trainingcache.Histogram getTtlOverduesSecHistogram();
  /**
   * <code>optional .speech.training_cache.Histogram ttl_overdues_sec_histogram = 8;</code>
   */
  com.google.speech.trainingcache.HistogramOrBuilder getTtlOverduesSecHistogramOrBuilder();

  /**
   * <code>optional int64 cleanup_time_usec = 9;</code>
   * @return Whether the cleanupTimeUsec field is set.
   */
  boolean hasCleanupTimeUsec();
  /**
   * <code>optional int64 cleanup_time_usec = 9;</code>
   * @return The cleanupTimeUsec.
   */
  long getCleanupTimeUsec();

  /**
   * <code>optional int64 cycle_length_usec = 10;</code>
   * @return Whether the cycleLengthUsec field is set.
   */
  boolean hasCycleLengthUsec();
  /**
   * <code>optional int64 cycle_length_usec = 10;</code>
   * @return The cycleLengthUsec.
   */
  long getCycleLengthUsec();
}
