// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech/soda/public/task.proto

package com.google.speech.soda;

public final class TaskProto {
  private TaskProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:speech.soda.Task)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .speech.soda.Task.TaskType type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .speech.soda.Task.TaskType type = 1;</code>
     * @return The type.
     */
    com.google.speech.soda.TaskProto.Task.TaskType getType();
  }
  /**
   * Protobuf type {@code speech.soda.Task}
   */
  public static final class Task extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:speech.soda.Task)
      TaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Task() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Task();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.speech.soda.TaskProto.internal_static_speech_soda_Task_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.speech.soda.TaskProto.internal_static_speech_soda_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.speech.soda.TaskProto.Task.class, com.google.speech.soda.TaskProto.Task.Builder.class);
    }

    /**
     * Protobuf enum {@code speech.soda.Task.TaskType}
     */
    public enum TaskType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEFAULT = 0;</code>
       */
      DEFAULT(0),
      /**
       * <code>AUDIO_LOGGING = 1;</code>
       */
      AUDIO_LOGGING(1),
      ;

      /**
       * <code>DEFAULT = 0;</code>
       */
      public static final int DEFAULT_VALUE = 0;
      /**
       * <code>AUDIO_LOGGING = 1;</code>
       */
      public static final int AUDIO_LOGGING_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TaskType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static TaskType forNumber(int value) {
        switch (value) {
          case 0: return DEFAULT;
          case 1: return AUDIO_LOGGING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TaskType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TaskType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TaskType>() {
              public TaskType findValueByNumber(int number) {
                return TaskType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.speech.soda.TaskProto.Task.getDescriptor().getEnumTypes().get(0);
      }

      private static final TaskType[] VALUES = values();

      public static TaskType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TaskType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:speech.soda.Task.TaskType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .speech.soda.Task.TaskType type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .speech.soda.Task.TaskType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.google.speech.soda.TaskProto.Task.TaskType getType() {
      @SuppressWarnings("deprecation")
      com.google.speech.soda.TaskProto.Task.TaskType result = com.google.speech.soda.TaskProto.Task.TaskType.valueOf(type_);
      return result == null ? com.google.speech.soda.TaskProto.Task.TaskType.DEFAULT : result;
    }

    public static com.google.speech.soda.TaskProto.Task parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.TaskProto.Task parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.TaskProto.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.TaskProto.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.TaskProto.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.TaskProto.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.TaskProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.speech.soda.TaskProto.Task prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code speech.soda.Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:speech.soda.Task)
        com.google.speech.soda.TaskProto.TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.speech.soda.TaskProto.internal_static_speech_soda_Task_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.speech.soda.TaskProto.internal_static_speech_soda_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.speech.soda.TaskProto.Task.class, com.google.speech.soda.TaskProto.Task.Builder.class);
      }

      // Construct using com.google.speech.soda.TaskProto.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.speech.soda.TaskProto.internal_static_speech_soda_Task_descriptor;
      }

      @java.lang.Override
      public com.google.speech.soda.TaskProto.Task getDefaultInstanceForType() {
        return com.google.speech.soda.TaskProto.Task.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.speech.soda.TaskProto.Task build() {
        com.google.speech.soda.TaskProto.Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.speech.soda.TaskProto.Task buildPartial() {
        com.google.speech.soda.TaskProto.Task result = new com.google.speech.soda.TaskProto.Task(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>optional .speech.soda.Task.TaskType type = 1;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .speech.soda.Task.TaskType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.google.speech.soda.TaskProto.Task.TaskType getType() {
        @SuppressWarnings("deprecation")
        com.google.speech.soda.TaskProto.Task.TaskType result = com.google.speech.soda.TaskProto.Task.TaskType.valueOf(type_);
        return result == null ? com.google.speech.soda.TaskProto.Task.TaskType.DEFAULT : result;
      }
      /**
       * <code>optional .speech.soda.Task.TaskType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.google.speech.soda.TaskProto.Task.TaskType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .speech.soda.Task.TaskType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:speech.soda.Task)
    }

    // @@protoc_insertion_point(class_scope:speech.soda.Task)
    private static final com.google.speech.soda.TaskProto.Task DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.speech.soda.TaskProto.Task();
    }

    public static com.google.speech.soda.TaskProto.Task getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Task>
        PARSER = new com.google.protobuf.AbstractParser<Task>() {
      @java.lang.Override
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Task> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.speech.soda.TaskProto.Task getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:speech.soda.TaskInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
     * @return Whether the authentication field is set.
     */
    @java.lang.Deprecated boolean hasAuthentication();
    /**
     * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
     * @return The authentication.
     */
    @java.lang.Deprecated com.google.speech.soda.AuthProto.Authentication getAuthentication();
    /**
     * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
     */
    @java.lang.Deprecated com.google.speech.soda.AuthProto.AuthenticationOrBuilder getAuthenticationOrBuilder();

    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    java.util.List<com.google.speech.soda.TaskProto.Task> 
        getTaskList();
    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    com.google.speech.soda.TaskProto.Task getTask(int index);
    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    int getTaskCount();
    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    java.util.List<? extends com.google.speech.soda.TaskProto.TaskOrBuilder> 
        getTaskOrBuilderList();
    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    com.google.speech.soda.TaskProto.TaskOrBuilder getTaskOrBuilder(
        int index);

    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    java.util.List<com.google.speech.soda.AuthProto.Authentication> 
        getAuthenticationsList();
    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    com.google.speech.soda.AuthProto.Authentication getAuthentications(int index);
    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    int getAuthenticationsCount();
    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    java.util.List<? extends com.google.speech.soda.AuthProto.AuthenticationOrBuilder> 
        getAuthenticationsOrBuilderList();
    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    com.google.speech.soda.AuthProto.AuthenticationOrBuilder getAuthenticationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code speech.soda.TaskInput}
   */
  public static final class TaskInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:speech.soda.TaskInput)
      TaskInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskInput.newBuilder() to construct.
    private TaskInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskInput() {
      task_ = java.util.Collections.emptyList();
      authentications_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskInput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.speech.soda.TaskProto.internal_static_speech_soda_TaskInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.speech.soda.TaskProto.internal_static_speech_soda_TaskInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.speech.soda.TaskProto.TaskInput.class, com.google.speech.soda.TaskProto.TaskInput.Builder.class);
    }

    private int bitField0_;
    public static final int AUTHENTICATION_FIELD_NUMBER = 1;
    private com.google.speech.soda.AuthProto.Authentication authentication_;
    /**
     * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
     * @return Whether the authentication field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasAuthentication() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
     * @return The authentication.
     */
    @java.lang.Override
    @java.lang.Deprecated public com.google.speech.soda.AuthProto.Authentication getAuthentication() {
      return authentication_ == null ? com.google.speech.soda.AuthProto.Authentication.getDefaultInstance() : authentication_;
    }
    /**
     * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
     */
    @java.lang.Override
    @java.lang.Deprecated public com.google.speech.soda.AuthProto.AuthenticationOrBuilder getAuthenticationOrBuilder() {
      return authentication_ == null ? com.google.speech.soda.AuthProto.Authentication.getDefaultInstance() : authentication_;
    }

    public static final int TASK_FIELD_NUMBER = 2;
    private java.util.List<com.google.speech.soda.TaskProto.Task> task_;
    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.speech.soda.TaskProto.Task> getTaskList() {
      return task_;
    }
    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.google.speech.soda.TaskProto.TaskOrBuilder> 
        getTaskOrBuilderList() {
      return task_;
    }
    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    @java.lang.Override
    public int getTaskCount() {
      return task_.size();
    }
    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    @java.lang.Override
    public com.google.speech.soda.TaskProto.Task getTask(int index) {
      return task_.get(index);
    }
    /**
     * <code>repeated .speech.soda.Task task = 2;</code>
     */
    @java.lang.Override
    public com.google.speech.soda.TaskProto.TaskOrBuilder getTaskOrBuilder(
        int index) {
      return task_.get(index);
    }

    public static final int AUTHENTICATIONS_FIELD_NUMBER = 3;
    private java.util.List<com.google.speech.soda.AuthProto.Authentication> authentications_;
    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.speech.soda.AuthProto.Authentication> getAuthenticationsList() {
      return authentications_;
    }
    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.google.speech.soda.AuthProto.AuthenticationOrBuilder> 
        getAuthenticationsOrBuilderList() {
      return authentications_;
    }
    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    @java.lang.Override
    public int getAuthenticationsCount() {
      return authentications_.size();
    }
    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    @java.lang.Override
    public com.google.speech.soda.AuthProto.Authentication getAuthentications(int index) {
      return authentications_.get(index);
    }
    /**
     * <code>repeated .speech.soda.Authentication authentications = 3;</code>
     */
    @java.lang.Override
    public com.google.speech.soda.AuthProto.AuthenticationOrBuilder getAuthenticationsOrBuilder(
        int index) {
      return authentications_.get(index);
    }

    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.TaskProto.TaskInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.speech.soda.TaskProto.TaskInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code speech.soda.TaskInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:speech.soda.TaskInput)
        com.google.speech.soda.TaskProto.TaskInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.speech.soda.TaskProto.internal_static_speech_soda_TaskInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.speech.soda.TaskProto.internal_static_speech_soda_TaskInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.speech.soda.TaskProto.TaskInput.class, com.google.speech.soda.TaskProto.TaskInput.Builder.class);
      }

      // Construct using com.google.speech.soda.TaskProto.TaskInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAuthenticationFieldBuilder();
          getTaskFieldBuilder();
          getAuthenticationsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (authenticationBuilder_ == null) {
          authentication_ = null;
        } else {
          authenticationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (taskBuilder_ == null) {
          task_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          taskBuilder_.clear();
        }
        if (authenticationsBuilder_ == null) {
          authentications_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          authenticationsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.speech.soda.TaskProto.internal_static_speech_soda_TaskInput_descriptor;
      }

      @java.lang.Override
      public com.google.speech.soda.TaskProto.TaskInput getDefaultInstanceForType() {
        return com.google.speech.soda.TaskProto.TaskInput.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.speech.soda.TaskProto.TaskInput build() {
        com.google.speech.soda.TaskProto.TaskInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.speech.soda.TaskProto.TaskInput buildPartial() {
        com.google.speech.soda.TaskProto.TaskInput result = new com.google.speech.soda.TaskProto.TaskInput(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (authenticationBuilder_ == null) {
            result.authentication_ = authentication_;
          } else {
            result.authentication_ = authenticationBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (taskBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            task_ = java.util.Collections.unmodifiableList(task_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.task_ = task_;
        } else {
          result.task_ = taskBuilder_.build();
        }
        if (authenticationsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            authentications_ = java.util.Collections.unmodifiableList(authentications_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.authentications_ = authentications_;
        } else {
          result.authentications_ = authenticationsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private com.google.speech.soda.AuthProto.Authentication authentication_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.speech.soda.AuthProto.Authentication, com.google.speech.soda.AuthProto.Authentication.Builder, com.google.speech.soda.AuthProto.AuthenticationOrBuilder> authenticationBuilder_;
      /**
       * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
       * @return Whether the authentication field is set.
       */
      @java.lang.Deprecated public boolean hasAuthentication() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
       * @return The authentication.
       */
      @java.lang.Deprecated public com.google.speech.soda.AuthProto.Authentication getAuthentication() {
        if (authenticationBuilder_ == null) {
          return authentication_ == null ? com.google.speech.soda.AuthProto.Authentication.getDefaultInstance() : authentication_;
        } else {
          return authenticationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setAuthentication(com.google.speech.soda.AuthProto.Authentication value) {
        if (authenticationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          authentication_ = value;
          onChanged();
        } else {
          authenticationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setAuthentication(
          com.google.speech.soda.AuthProto.Authentication.Builder builderForValue) {
        if (authenticationBuilder_ == null) {
          authentication_ = builderForValue.build();
          onChanged();
        } else {
          authenticationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder mergeAuthentication(com.google.speech.soda.AuthProto.Authentication value) {
        if (authenticationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              authentication_ != null &&
              authentication_ != com.google.speech.soda.AuthProto.Authentication.getDefaultInstance()) {
            authentication_ =
              com.google.speech.soda.AuthProto.Authentication.newBuilder(authentication_).mergeFrom(value).buildPartial();
          } else {
            authentication_ = value;
          }
          onChanged();
        } else {
          authenticationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearAuthentication() {
        if (authenticationBuilder_ == null) {
          authentication_ = null;
          onChanged();
        } else {
          authenticationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public com.google.speech.soda.AuthProto.Authentication.Builder getAuthenticationBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAuthenticationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public com.google.speech.soda.AuthProto.AuthenticationOrBuilder getAuthenticationOrBuilder() {
        if (authenticationBuilder_ != null) {
          return authenticationBuilder_.getMessageOrBuilder();
        } else {
          return authentication_ == null ?
              com.google.speech.soda.AuthProto.Authentication.getDefaultInstance() : authentication_;
        }
      }
      /**
       * <code>optional .speech.soda.Authentication authentication = 1 [deprecated = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.speech.soda.AuthProto.Authentication, com.google.speech.soda.AuthProto.Authentication.Builder, com.google.speech.soda.AuthProto.AuthenticationOrBuilder> 
          getAuthenticationFieldBuilder() {
        if (authenticationBuilder_ == null) {
          authenticationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.speech.soda.AuthProto.Authentication, com.google.speech.soda.AuthProto.Authentication.Builder, com.google.speech.soda.AuthProto.AuthenticationOrBuilder>(
                  getAuthentication(),
                  getParentForChildren(),
                  isClean());
          authentication_ = null;
        }
        return authenticationBuilder_;
      }

      private java.util.List<com.google.speech.soda.TaskProto.Task> task_ =
        java.util.Collections.emptyList();
      private void ensureTaskIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          task_ = new java.util.ArrayList<com.google.speech.soda.TaskProto.Task>(task_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.speech.soda.TaskProto.Task, com.google.speech.soda.TaskProto.Task.Builder, com.google.speech.soda.TaskProto.TaskOrBuilder> taskBuilder_;

      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public java.util.List<com.google.speech.soda.TaskProto.Task> getTaskList() {
        if (taskBuilder_ == null) {
          return java.util.Collections.unmodifiableList(task_);
        } else {
          return taskBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public int getTaskCount() {
        if (taskBuilder_ == null) {
          return task_.size();
        } else {
          return taskBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public com.google.speech.soda.TaskProto.Task getTask(int index) {
        if (taskBuilder_ == null) {
          return task_.get(index);
        } else {
          return taskBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public Builder setTask(
          int index, com.google.speech.soda.TaskProto.Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskIsMutable();
          task_.set(index, value);
          onChanged();
        } else {
          taskBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public Builder setTask(
          int index, com.google.speech.soda.TaskProto.Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.set(index, builderForValue.build());
          onChanged();
        } else {
          taskBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public Builder addTask(com.google.speech.soda.TaskProto.Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskIsMutable();
          task_.add(value);
          onChanged();
        } else {
          taskBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public Builder addTask(
          int index, com.google.speech.soda.TaskProto.Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskIsMutable();
          task_.add(index, value);
          onChanged();
        } else {
          taskBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public Builder addTask(
          com.google.speech.soda.TaskProto.Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.add(builderForValue.build());
          onChanged();
        } else {
          taskBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public Builder addTask(
          int index, com.google.speech.soda.TaskProto.Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.add(index, builderForValue.build());
          onChanged();
        } else {
          taskBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public Builder addAllTask(
          java.lang.Iterable<? extends com.google.speech.soda.TaskProto.Task> values) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, task_);
          onChanged();
        } else {
          taskBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public Builder clearTask() {
        if (taskBuilder_ == null) {
          task_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          taskBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public Builder removeTask(int index) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.remove(index);
          onChanged();
        } else {
          taskBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public com.google.speech.soda.TaskProto.Task.Builder getTaskBuilder(
          int index) {
        return getTaskFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public com.google.speech.soda.TaskProto.TaskOrBuilder getTaskOrBuilder(
          int index) {
        if (taskBuilder_ == null) {
          return task_.get(index);  } else {
          return taskBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public java.util.List<? extends com.google.speech.soda.TaskProto.TaskOrBuilder> 
           getTaskOrBuilderList() {
        if (taskBuilder_ != null) {
          return taskBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(task_);
        }
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public com.google.speech.soda.TaskProto.Task.Builder addTaskBuilder() {
        return getTaskFieldBuilder().addBuilder(
            com.google.speech.soda.TaskProto.Task.getDefaultInstance());
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public com.google.speech.soda.TaskProto.Task.Builder addTaskBuilder(
          int index) {
        return getTaskFieldBuilder().addBuilder(
            index, com.google.speech.soda.TaskProto.Task.getDefaultInstance());
      }
      /**
       * <code>repeated .speech.soda.Task task = 2;</code>
       */
      public java.util.List<com.google.speech.soda.TaskProto.Task.Builder> 
           getTaskBuilderList() {
        return getTaskFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.speech.soda.TaskProto.Task, com.google.speech.soda.TaskProto.Task.Builder, com.google.speech.soda.TaskProto.TaskOrBuilder> 
          getTaskFieldBuilder() {
        if (taskBuilder_ == null) {
          taskBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.speech.soda.TaskProto.Task, com.google.speech.soda.TaskProto.Task.Builder, com.google.speech.soda.TaskProto.TaskOrBuilder>(
                  task_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          task_ = null;
        }
        return taskBuilder_;
      }

      private java.util.List<com.google.speech.soda.AuthProto.Authentication> authentications_ =
        java.util.Collections.emptyList();
      private void ensureAuthenticationsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          authentications_ = new java.util.ArrayList<com.google.speech.soda.AuthProto.Authentication>(authentications_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.speech.soda.AuthProto.Authentication, com.google.speech.soda.AuthProto.Authentication.Builder, com.google.speech.soda.AuthProto.AuthenticationOrBuilder> authenticationsBuilder_;

      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public java.util.List<com.google.speech.soda.AuthProto.Authentication> getAuthenticationsList() {
        if (authenticationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(authentications_);
        } else {
          return authenticationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public int getAuthenticationsCount() {
        if (authenticationsBuilder_ == null) {
          return authentications_.size();
        } else {
          return authenticationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public com.google.speech.soda.AuthProto.Authentication getAuthentications(int index) {
        if (authenticationsBuilder_ == null) {
          return authentications_.get(index);
        } else {
          return authenticationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public Builder setAuthentications(
          int index, com.google.speech.soda.AuthProto.Authentication value) {
        if (authenticationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthenticationsIsMutable();
          authentications_.set(index, value);
          onChanged();
        } else {
          authenticationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public Builder setAuthentications(
          int index, com.google.speech.soda.AuthProto.Authentication.Builder builderForValue) {
        if (authenticationsBuilder_ == null) {
          ensureAuthenticationsIsMutable();
          authentications_.set(index, builderForValue.build());
          onChanged();
        } else {
          authenticationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public Builder addAuthentications(com.google.speech.soda.AuthProto.Authentication value) {
        if (authenticationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthenticationsIsMutable();
          authentications_.add(value);
          onChanged();
        } else {
          authenticationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public Builder addAuthentications(
          int index, com.google.speech.soda.AuthProto.Authentication value) {
        if (authenticationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthenticationsIsMutable();
          authentications_.add(index, value);
          onChanged();
        } else {
          authenticationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public Builder addAuthentications(
          com.google.speech.soda.AuthProto.Authentication.Builder builderForValue) {
        if (authenticationsBuilder_ == null) {
          ensureAuthenticationsIsMutable();
          authentications_.add(builderForValue.build());
          onChanged();
        } else {
          authenticationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public Builder addAuthentications(
          int index, com.google.speech.soda.AuthProto.Authentication.Builder builderForValue) {
        if (authenticationsBuilder_ == null) {
          ensureAuthenticationsIsMutable();
          authentications_.add(index, builderForValue.build());
          onChanged();
        } else {
          authenticationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public Builder addAllAuthentications(
          java.lang.Iterable<? extends com.google.speech.soda.AuthProto.Authentication> values) {
        if (authenticationsBuilder_ == null) {
          ensureAuthenticationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, authentications_);
          onChanged();
        } else {
          authenticationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public Builder clearAuthentications() {
        if (authenticationsBuilder_ == null) {
          authentications_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          authenticationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public Builder removeAuthentications(int index) {
        if (authenticationsBuilder_ == null) {
          ensureAuthenticationsIsMutable();
          authentications_.remove(index);
          onChanged();
        } else {
          authenticationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public com.google.speech.soda.AuthProto.Authentication.Builder getAuthenticationsBuilder(
          int index) {
        return getAuthenticationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public com.google.speech.soda.AuthProto.AuthenticationOrBuilder getAuthenticationsOrBuilder(
          int index) {
        if (authenticationsBuilder_ == null) {
          return authentications_.get(index);  } else {
          return authenticationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public java.util.List<? extends com.google.speech.soda.AuthProto.AuthenticationOrBuilder> 
           getAuthenticationsOrBuilderList() {
        if (authenticationsBuilder_ != null) {
          return authenticationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(authentications_);
        }
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public com.google.speech.soda.AuthProto.Authentication.Builder addAuthenticationsBuilder() {
        return getAuthenticationsFieldBuilder().addBuilder(
            com.google.speech.soda.AuthProto.Authentication.getDefaultInstance());
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public com.google.speech.soda.AuthProto.Authentication.Builder addAuthenticationsBuilder(
          int index) {
        return getAuthenticationsFieldBuilder().addBuilder(
            index, com.google.speech.soda.AuthProto.Authentication.getDefaultInstance());
      }
      /**
       * <code>repeated .speech.soda.Authentication authentications = 3;</code>
       */
      public java.util.List<com.google.speech.soda.AuthProto.Authentication.Builder> 
           getAuthenticationsBuilderList() {
        return getAuthenticationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.speech.soda.AuthProto.Authentication, com.google.speech.soda.AuthProto.Authentication.Builder, com.google.speech.soda.AuthProto.AuthenticationOrBuilder> 
          getAuthenticationsFieldBuilder() {
        if (authenticationsBuilder_ == null) {
          authenticationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.speech.soda.AuthProto.Authentication, com.google.speech.soda.AuthProto.Authentication.Builder, com.google.speech.soda.AuthProto.AuthenticationOrBuilder>(
                  authentications_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          authentications_ = null;
        }
        return authenticationsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:speech.soda.TaskInput)
    }

    // @@protoc_insertion_point(class_scope:speech.soda.TaskInput)
    private static final com.google.speech.soda.TaskProto.TaskInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.speech.soda.TaskProto.TaskInput();
    }

    public static com.google.speech.soda.TaskProto.TaskInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TaskInput>
        PARSER = new com.google.protobuf.AbstractParser<TaskInput>() {
      @java.lang.Override
      public TaskInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TaskInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.speech.soda.TaskProto.TaskInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_soda_Task_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_soda_Task_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_soda_TaskInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_soda_TaskInput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035speech/soda/public/task.proto\022\013speech." +
      "soda\032\035speech/soda/public/auth.proto\"\\\n\004T" +
      "ask\022(\n\004type\030\001 \001(\0162\032.speech.soda.Task.Tas" +
      "kType\"*\n\010TaskType\022\013\n\007DEFAULT\020\000\022\021\n\rAUDIO_" +
      "LOGGING\020\001\"\233\001\n\tTaskInput\0227\n\016authenticatio" +
      "n\030\001 \001(\0132\033.speech.soda.AuthenticationB\002\030\001" +
      "\022\037\n\004task\030\002 \003(\0132\021.speech.soda.Task\0224\n\017aut" +
      "hentications\030\003 \003(\0132\033.speech.soda.Authent" +
      "icationB+\n\026com.google.speech.sodaB\tTaskP" +
      "rotoH\002\242\002\003SDA"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.speech.soda.AuthProto.getDescriptor(),
        });
    internal_static_speech_soda_Task_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_speech_soda_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_soda_Task_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_speech_soda_TaskInput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_speech_soda_TaskInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_soda_TaskInput_descriptor,
        new java.lang.String[] { "Authentication", "Task", "Authentications", });
    com.google.speech.soda.AuthProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
