// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech/soda/public/extensions/voice-match-enrollment-extension.proto

package com.google.speech.soda;

public final class VoiceMatchEnrollmentExtensionProto {
  private VoiceMatchEnrollmentExtensionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.clientConfigId);
    registry.add(com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.coreConfigId);
    registry.add(com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.id);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VoiceMatchCaptureRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:speech.soda.VoiceMatchCaptureRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
     * @return Whether the enrollmentRequest field is set.
     */
    boolean hasEnrollmentRequest();
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
     * @return The enrollmentRequest.
     */
    com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest getEnrollmentRequest();
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
     */
    com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequestOrBuilder getEnrollmentRequestOrBuilder();
  }
  /**
   * Protobuf type {@code speech.soda.VoiceMatchCaptureRequest}
   */
  public static final class VoiceMatchCaptureRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:speech.soda.VoiceMatchCaptureRequest)
      VoiceMatchCaptureRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoiceMatchCaptureRequest.newBuilder() to construct.
    private VoiceMatchCaptureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoiceMatchCaptureRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoiceMatchCaptureRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.class, com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ENROLLMENT_REQUEST_FIELD_NUMBER = 1;
    private com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest enrollmentRequest_;
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
     * @return Whether the enrollmentRequest field is set.
     */
    @java.lang.Override
    public boolean hasEnrollmentRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
     * @return The enrollmentRequest.
     */
    @java.lang.Override
    public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest getEnrollmentRequest() {
      return enrollmentRequest_ == null ? com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.getDefaultInstance() : enrollmentRequest_;
    }
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
     */
    @java.lang.Override
    public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequestOrBuilder getEnrollmentRequestOrBuilder() {
      return enrollmentRequest_ == null ? com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.getDefaultInstance() : enrollmentRequest_;
    }

    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code speech.soda.VoiceMatchCaptureRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:speech.soda.VoiceMatchCaptureRequest)
        com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.class, com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.Builder.class);
      }

      // Construct using com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEnrollmentRequestFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (enrollmentRequestBuilder_ == null) {
          enrollmentRequest_ = null;
        } else {
          enrollmentRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureRequest_descriptor;
      }

      @java.lang.Override
      public com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest getDefaultInstanceForType() {
        return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest build() {
        com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest buildPartial() {
        com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest result = new com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (enrollmentRequestBuilder_ == null) {
            result.enrollmentRequest_ = enrollmentRequest_;
          } else {
            result.enrollmentRequest_ = enrollmentRequestBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest enrollmentRequest_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.Builder, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequestOrBuilder> enrollmentRequestBuilder_;
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
       * @return Whether the enrollmentRequest field is set.
       */
      public boolean hasEnrollmentRequest() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
       * @return The enrollmentRequest.
       */
      public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest getEnrollmentRequest() {
        if (enrollmentRequestBuilder_ == null) {
          return enrollmentRequest_ == null ? com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.getDefaultInstance() : enrollmentRequest_;
        } else {
          return enrollmentRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
       */
      public Builder setEnrollmentRequest(com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest value) {
        if (enrollmentRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          enrollmentRequest_ = value;
          onChanged();
        } else {
          enrollmentRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
       */
      public Builder setEnrollmentRequest(
          com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.Builder builderForValue) {
        if (enrollmentRequestBuilder_ == null) {
          enrollmentRequest_ = builderForValue.build();
          onChanged();
        } else {
          enrollmentRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
       */
      public Builder mergeEnrollmentRequest(com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest value) {
        if (enrollmentRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              enrollmentRequest_ != null &&
              enrollmentRequest_ != com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.getDefaultInstance()) {
            enrollmentRequest_ =
              com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.newBuilder(enrollmentRequest_).mergeFrom(value).buildPartial();
          } else {
            enrollmentRequest_ = value;
          }
          onChanged();
        } else {
          enrollmentRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
       */
      public Builder clearEnrollmentRequest() {
        if (enrollmentRequestBuilder_ == null) {
          enrollmentRequest_ = null;
          onChanged();
        } else {
          enrollmentRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
       */
      public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.Builder getEnrollmentRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEnrollmentRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
       */
      public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequestOrBuilder getEnrollmentRequestOrBuilder() {
        if (enrollmentRequestBuilder_ != null) {
          return enrollmentRequestBuilder_.getMessageOrBuilder();
        } else {
          return enrollmentRequest_ == null ?
              com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.getDefaultInstance() : enrollmentRequest_;
        }
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentRequest enrollment_request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.Builder, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequestOrBuilder> 
          getEnrollmentRequestFieldBuilder() {
        if (enrollmentRequestBuilder_ == null) {
          enrollmentRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequest.Builder, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentRequestOrBuilder>(
                  getEnrollmentRequest(),
                  getParentForChildren(),
                  isClean());
          enrollmentRequest_ = null;
        }
        return enrollmentRequestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:speech.soda.VoiceMatchCaptureRequest)
    }

    // @@protoc_insertion_point(class_scope:speech.soda.VoiceMatchCaptureRequest)
    private static final com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest();
    }

    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<VoiceMatchCaptureRequest>
        PARSER = new com.google.protobuf.AbstractParser<VoiceMatchCaptureRequest>() {
      @java.lang.Override
      public VoiceMatchCaptureRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VoiceMatchCaptureRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoiceMatchCaptureRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int CLIENT_CONFIG_ID_FIELD_NUMBER = 311836513;
    /**
     * <code>extend .speech.soda.client.SodaClientConfig { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.google.speech.soda.client.SodaClientConfigProto.SodaClientConfig,
        com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest> clientConfigId = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.getDefaultInstance(),
          0,
          com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.class,
          com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.getDefaultInstance());
    public static final int CORE_CONFIG_ID_FIELD_NUMBER = 311836515;
    /**
     * <code>extend .speech.soda.SodaCoreConfig { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.google.speech.soda.SodaCoreConfigProto.SodaCoreConfig,
        com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest> coreConfigId = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.getDefaultInstance(),
          1,
          com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.class,
          com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureRequest.getDefaultInstance());
  }

  public interface VoiceMatchCaptureResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:speech.soda.VoiceMatchCaptureResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
     * @return Whether the enrollmentResponse field is set.
     */
    boolean hasEnrollmentResponse();
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
     * @return The enrollmentResponse.
     */
    com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse getEnrollmentResponse();
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
     */
    com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponseOrBuilder getEnrollmentResponseOrBuilder();
  }
  /**
   * Protobuf type {@code speech.soda.VoiceMatchCaptureResponse}
   */
  public static final class VoiceMatchCaptureResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:speech.soda.VoiceMatchCaptureResponse)
      VoiceMatchCaptureResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoiceMatchCaptureResponse.newBuilder() to construct.
    private VoiceMatchCaptureResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoiceMatchCaptureResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoiceMatchCaptureResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.class, com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ENROLLMENT_RESPONSE_FIELD_NUMBER = 1;
    private com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse enrollmentResponse_;
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
     * @return Whether the enrollmentResponse field is set.
     */
    @java.lang.Override
    public boolean hasEnrollmentResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
     * @return The enrollmentResponse.
     */
    @java.lang.Override
    public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse getEnrollmentResponse() {
      return enrollmentResponse_ == null ? com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.getDefaultInstance() : enrollmentResponse_;
    }
    /**
     * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
     */
    @java.lang.Override
    public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponseOrBuilder getEnrollmentResponseOrBuilder() {
      return enrollmentResponse_ == null ? com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.getDefaultInstance() : enrollmentResponse_;
    }

    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code speech.soda.VoiceMatchCaptureResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:speech.soda.VoiceMatchCaptureResponse)
        com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.class, com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.Builder.class);
      }

      // Construct using com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEnrollmentResponseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (enrollmentResponseBuilder_ == null) {
          enrollmentResponse_ = null;
        } else {
          enrollmentResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.internal_static_speech_soda_VoiceMatchCaptureResponse_descriptor;
      }

      @java.lang.Override
      public com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse getDefaultInstanceForType() {
        return com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse build() {
        com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse buildPartial() {
        com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse result = new com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (enrollmentResponseBuilder_ == null) {
            result.enrollmentResponse_ = enrollmentResponse_;
          } else {
            result.enrollmentResponse_ = enrollmentResponseBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse enrollmentResponse_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.Builder, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponseOrBuilder> enrollmentResponseBuilder_;
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
       * @return Whether the enrollmentResponse field is set.
       */
      public boolean hasEnrollmentResponse() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
       * @return The enrollmentResponse.
       */
      public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse getEnrollmentResponse() {
        if (enrollmentResponseBuilder_ == null) {
          return enrollmentResponse_ == null ? com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.getDefaultInstance() : enrollmentResponse_;
        } else {
          return enrollmentResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
       */
      public Builder setEnrollmentResponse(com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse value) {
        if (enrollmentResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          enrollmentResponse_ = value;
          onChanged();
        } else {
          enrollmentResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
       */
      public Builder setEnrollmentResponse(
          com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.Builder builderForValue) {
        if (enrollmentResponseBuilder_ == null) {
          enrollmentResponse_ = builderForValue.build();
          onChanged();
        } else {
          enrollmentResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
       */
      public Builder mergeEnrollmentResponse(com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse value) {
        if (enrollmentResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              enrollmentResponse_ != null &&
              enrollmentResponse_ != com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.getDefaultInstance()) {
            enrollmentResponse_ =
              com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.newBuilder(enrollmentResponse_).mergeFrom(value).buildPartial();
          } else {
            enrollmentResponse_ = value;
          }
          onChanged();
        } else {
          enrollmentResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
       */
      public Builder clearEnrollmentResponse() {
        if (enrollmentResponseBuilder_ == null) {
          enrollmentResponse_ = null;
          onChanged();
        } else {
          enrollmentResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
       */
      public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.Builder getEnrollmentResponseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEnrollmentResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
       */
      public com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponseOrBuilder getEnrollmentResponseOrBuilder() {
        if (enrollmentResponseBuilder_ != null) {
          return enrollmentResponseBuilder_.getMessageOrBuilder();
        } else {
          return enrollmentResponse_ == null ?
              com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.getDefaultInstance() : enrollmentResponse_;
        }
      }
      /**
       * <code>optional .speech.s3.VoiceMatchEnrollmentResponse enrollment_response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.Builder, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponseOrBuilder> 
          getEnrollmentResponseFieldBuilder() {
        if (enrollmentResponseBuilder_ == null) {
          enrollmentResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponse.Builder, com.google.speech.s3.VoiceMatchEnrollment.VoiceMatchEnrollmentResponseOrBuilder>(
                  getEnrollmentResponse(),
                  getParentForChildren(),
                  isClean());
          enrollmentResponse_ = null;
        }
        return enrollmentResponseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:speech.soda.VoiceMatchCaptureResponse)
    }

    // @@protoc_insertion_point(class_scope:speech.soda.VoiceMatchCaptureResponse)
    private static final com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse();
    }

    public static com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<VoiceMatchCaptureResponse>
        PARSER = new com.google.protobuf.AbstractParser<VoiceMatchCaptureResponse>() {
      @java.lang.Override
      public VoiceMatchCaptureResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VoiceMatchCaptureResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoiceMatchCaptureResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int ID_FIELD_NUMBER = 311836511;
    /**
     * <code>extend .speech.soda.VoiceMatchEnrollmentEvent { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.google.speech.soda.SpeakerIdProto.VoiceMatchEnrollmentEvent,
        com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse> id = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.getDefaultInstance(),
          0,
          com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.class,
          com.google.speech.soda.VoiceMatchEnrollmentExtensionProto.VoiceMatchCaptureResponse.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_soda_VoiceMatchCaptureRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_soda_VoiceMatchCaptureRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_soda_VoiceMatchCaptureResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_soda_VoiceMatchCaptureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nDspeech/soda/public/extensions/voice-ma" +
      "tch-enrollment-extension.proto\022\013speech.s" +
      "oda\032Mspeech/service/s3/services/assistan" +
      "t/voice_match/voice-match-enrollment.pro" +
      "to\032+speech/soda/public/soda_client_confi" +
      "g.proto\032)speech/soda/public/soda_core_co" +
      "nfig.proto\032#speech/soda/public/speaker_i" +
      "d.proto\"\251\002\n\030VoiceMatchCaptureRequest\022B\n\022" +
      "enrollment_request\030\001 \001(\0132&.speech.s3.Voi" +
      "ceMatchEnrollmentRequest2i\n\020client_confi" +
      "g_id\022$.speech.soda.client.SodaClientConf" +
      "ig\030\341\376\330\224\001 \001(\0132%.speech.soda.VoiceMatchCap" +
      "tureRequest2^\n\016core_config_id\022\033.speech.s" +
      "oda.SodaCoreConfig\030\343\376\330\224\001 \001(\0132%.speech.so" +
      "da.VoiceMatchCaptureRequest\"\301\001\n\031VoiceMat" +
      "chCaptureResponse\022D\n\023enrollment_response" +
      "\030\001 \001(\0132\'.speech.s3.VoiceMatchEnrollmentR" +
      "esponse2^\n\002id\022&.speech.soda.VoiceMatchEn" +
      "rollmentEvent\030\337\376\330\224\001 \001(\0132&.speech.soda.Vo" +
      "iceMatchCaptureResponseBD\n\026com.google.sp" +
      "eech.sodaB\"VoiceMatchEnrollmentExtension" +
      "ProtoH\002\242\002\003SDA"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.speech.s3.VoiceMatchEnrollment.getDescriptor(),
          com.google.speech.soda.client.SodaClientConfigProto.getDescriptor(),
          com.google.speech.soda.SodaCoreConfigProto.getDescriptor(),
          com.google.speech.soda.SpeakerIdProto.getDescriptor(),
        });
    internal_static_speech_soda_VoiceMatchCaptureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_speech_soda_VoiceMatchCaptureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_soda_VoiceMatchCaptureRequest_descriptor,
        new java.lang.String[] { "EnrollmentRequest", });
    internal_static_speech_soda_VoiceMatchCaptureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_speech_soda_VoiceMatchCaptureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_soda_VoiceMatchCaptureResponse_descriptor,
        new java.lang.String[] { "EnrollmentResponse", });
    com.google.speech.s3.VoiceMatchEnrollment.getDescriptor();
    com.google.speech.soda.client.SodaClientConfigProto.getDescriptor();
    com.google.speech.soda.SodaCoreConfigProto.getDescriptor();
    com.google.speech.soda.SpeakerIdProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
