// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logs/proto/speech/service/recognizer_log.proto

package com.google.speech.logs;

/**
 * Protobuf type {@code speech.logs.AudioStream}
 */
public final class AudioStream extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:speech.logs.AudioStream)
    AudioStreamOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AudioStream.newBuilder() to construct.
  private AudioStream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AudioStream() {
    encodedWaveform_ = com.google.protobuf.ByteString.EMPTY;
    audioEncoding_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AudioStream();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.speech.logs.RecognizerOuterClass.internal_static_speech_logs_AudioStream_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.speech.logs.RecognizerOuterClass.internal_static_speech_logs_AudioStream_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.speech.logs.AudioStream.class, com.google.speech.logs.AudioStream.Builder.class);
  }

  private int bitField0_;
  public static final int ENCODED_WAVEFORM_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString encodedWaveform_;
  /**
   * <code>optional bytes encoded_waveform = 1;</code>
   * @return Whether the encodedWaveform field is set.
   */
  @java.lang.Override
  public boolean hasEncodedWaveform() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bytes encoded_waveform = 1;</code>
   * @return The encodedWaveform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncodedWaveform() {
    return encodedWaveform_;
  }

  public static final int SAMPLE_RATE_FIELD_NUMBER = 3;
  private float sampleRate_;
  /**
   * <code>optional float sample_rate = 3;</code>
   * @return Whether the sampleRate field is set.
   */
  @java.lang.Override
  public boolean hasSampleRate() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional float sample_rate = 3;</code>
   * @return The sampleRate.
   */
  @java.lang.Override
  public float getSampleRate() {
    return sampleRate_;
  }

  public static final int AUDIO_ENCODING_FIELD_NUMBER = 4;
  private int audioEncoding_;
  /**
   * <code>optional .speech.logs.RecognizerLog.AudioEncodingType audio_encoding = 4;</code>
   * @return Whether the audioEncoding field is set.
   */
  @java.lang.Override public boolean hasAudioEncoding() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .speech.logs.RecognizerLog.AudioEncodingType audio_encoding = 4;</code>
   * @return The audioEncoding.
   */
  @java.lang.Override public com.google.speech.logs.RecognizerLog.AudioEncodingType getAudioEncoding() {
    @SuppressWarnings("deprecation")
    com.google.speech.logs.RecognizerLog.AudioEncodingType result = com.google.speech.logs.RecognizerLog.AudioEncodingType.valueOf(audioEncoding_);
    return result == null ? com.google.speech.logs.RecognizerLog.AudioEncodingType.LINEAR16 : result;
  }

  public static final int DESC_FIELD_NUMBER = 5;
  private com.google.speech.logs.AudioStreamDescriptor desc_;
  /**
   * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
   * @return Whether the desc field is set.
   */
  @java.lang.Override
  public boolean hasDesc() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
   * @return The desc.
   */
  @java.lang.Override
  public com.google.speech.logs.AudioStreamDescriptor getDesc() {
    return desc_ == null ? com.google.speech.logs.AudioStreamDescriptor.getDefaultInstance() : desc_;
  }
  /**
   * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
   */
  @java.lang.Override
  public com.google.speech.logs.AudioStreamDescriptorOrBuilder getDescOrBuilder() {
    return desc_ == null ? com.google.speech.logs.AudioStreamDescriptor.getDefaultInstance() : desc_;
  }

  public static com.google.speech.logs.AudioStream parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.speech.logs.AudioStream parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.speech.logs.AudioStream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.speech.logs.AudioStream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.speech.logs.AudioStream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.speech.logs.AudioStream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.speech.logs.AudioStream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.speech.logs.AudioStream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.speech.logs.AudioStream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.speech.logs.AudioStream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.speech.logs.AudioStream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.speech.logs.AudioStream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.speech.logs.AudioStream prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code speech.logs.AudioStream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:speech.logs.AudioStream)
      com.google.speech.logs.AudioStreamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.speech.logs.RecognizerOuterClass.internal_static_speech_logs_AudioStream_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.speech.logs.RecognizerOuterClass.internal_static_speech_logs_AudioStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.speech.logs.AudioStream.class, com.google.speech.logs.AudioStream.Builder.class);
    }

    // Construct using com.google.speech.logs.AudioStream.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDescFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      encodedWaveform_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      sampleRate_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000002);
      audioEncoding_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (descBuilder_ == null) {
        desc_ = null;
      } else {
        descBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.speech.logs.RecognizerOuterClass.internal_static_speech_logs_AudioStream_descriptor;
    }

    @java.lang.Override
    public com.google.speech.logs.AudioStream getDefaultInstanceForType() {
      return com.google.speech.logs.AudioStream.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.speech.logs.AudioStream build() {
      com.google.speech.logs.AudioStream result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.speech.logs.AudioStream buildPartial() {
      com.google.speech.logs.AudioStream result = new com.google.speech.logs.AudioStream(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.encodedWaveform_ = encodedWaveform_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sampleRate_ = sampleRate_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.audioEncoding_ = audioEncoding_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (descBuilder_ == null) {
          result.desc_ = desc_;
        } else {
          result.desc_ = descBuilder_.build();
        }
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private com.google.protobuf.ByteString encodedWaveform_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes encoded_waveform = 1;</code>
     * @return Whether the encodedWaveform field is set.
     */
    @java.lang.Override
    public boolean hasEncodedWaveform() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes encoded_waveform = 1;</code>
     * @return The encodedWaveform.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncodedWaveform() {
      return encodedWaveform_;
    }
    /**
     * <code>optional bytes encoded_waveform = 1;</code>
     * @param value The encodedWaveform to set.
     * @return This builder for chaining.
     */
    public Builder setEncodedWaveform(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      encodedWaveform_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes encoded_waveform = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncodedWaveform() {
      bitField0_ = (bitField0_ & ~0x00000001);
      encodedWaveform_ = getDefaultInstance().getEncodedWaveform();
      onChanged();
      return this;
    }

    private float sampleRate_ ;
    /**
     * <code>optional float sample_rate = 3;</code>
     * @return Whether the sampleRate field is set.
     */
    @java.lang.Override
    public boolean hasSampleRate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float sample_rate = 3;</code>
     * @return The sampleRate.
     */
    @java.lang.Override
    public float getSampleRate() {
      return sampleRate_;
    }
    /**
     * <code>optional float sample_rate = 3;</code>
     * @param value The sampleRate to set.
     * @return This builder for chaining.
     */
    public Builder setSampleRate(float value) {
      bitField0_ |= 0x00000002;
      sampleRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float sample_rate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleRate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sampleRate_ = 0F;
      onChanged();
      return this;
    }

    private int audioEncoding_ = 0;
    /**
     * <code>optional .speech.logs.RecognizerLog.AudioEncodingType audio_encoding = 4;</code>
     * @return Whether the audioEncoding field is set.
     */
    @java.lang.Override public boolean hasAudioEncoding() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .speech.logs.RecognizerLog.AudioEncodingType audio_encoding = 4;</code>
     * @return The audioEncoding.
     */
    @java.lang.Override
    public com.google.speech.logs.RecognizerLog.AudioEncodingType getAudioEncoding() {
      @SuppressWarnings("deprecation")
      com.google.speech.logs.RecognizerLog.AudioEncodingType result = com.google.speech.logs.RecognizerLog.AudioEncodingType.valueOf(audioEncoding_);
      return result == null ? com.google.speech.logs.RecognizerLog.AudioEncodingType.LINEAR16 : result;
    }
    /**
     * <code>optional .speech.logs.RecognizerLog.AudioEncodingType audio_encoding = 4;</code>
     * @param value The audioEncoding to set.
     * @return This builder for chaining.
     */
    public Builder setAudioEncoding(com.google.speech.logs.RecognizerLog.AudioEncodingType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      audioEncoding_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .speech.logs.RecognizerLog.AudioEncodingType audio_encoding = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudioEncoding() {
      bitField0_ = (bitField0_ & ~0x00000004);
      audioEncoding_ = 0;
      onChanged();
      return this;
    }

    private com.google.speech.logs.AudioStreamDescriptor desc_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.speech.logs.AudioStreamDescriptor, com.google.speech.logs.AudioStreamDescriptor.Builder, com.google.speech.logs.AudioStreamDescriptorOrBuilder> descBuilder_;
    /**
     * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
     * @return Whether the desc field is set.
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
     * @return The desc.
     */
    public com.google.speech.logs.AudioStreamDescriptor getDesc() {
      if (descBuilder_ == null) {
        return desc_ == null ? com.google.speech.logs.AudioStreamDescriptor.getDefaultInstance() : desc_;
      } else {
        return descBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
     */
    public Builder setDesc(com.google.speech.logs.AudioStreamDescriptor value) {
      if (descBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        desc_ = value;
        onChanged();
      } else {
        descBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
     */
    public Builder setDesc(
        com.google.speech.logs.AudioStreamDescriptor.Builder builderForValue) {
      if (descBuilder_ == null) {
        desc_ = builderForValue.build();
        onChanged();
      } else {
        descBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
     */
    public Builder mergeDesc(com.google.speech.logs.AudioStreamDescriptor value) {
      if (descBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            desc_ != null &&
            desc_ != com.google.speech.logs.AudioStreamDescriptor.getDefaultInstance()) {
          desc_ =
            com.google.speech.logs.AudioStreamDescriptor.newBuilder(desc_).mergeFrom(value).buildPartial();
        } else {
          desc_ = value;
        }
        onChanged();
      } else {
        descBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
     */
    public Builder clearDesc() {
      if (descBuilder_ == null) {
        desc_ = null;
        onChanged();
      } else {
        descBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
     */
    public com.google.speech.logs.AudioStreamDescriptor.Builder getDescBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getDescFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
     */
    public com.google.speech.logs.AudioStreamDescriptorOrBuilder getDescOrBuilder() {
      if (descBuilder_ != null) {
        return descBuilder_.getMessageOrBuilder();
      } else {
        return desc_ == null ?
            com.google.speech.logs.AudioStreamDescriptor.getDefaultInstance() : desc_;
      }
    }
    /**
     * <code>optional .speech.logs.AudioStreamDescriptor desc = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.speech.logs.AudioStreamDescriptor, com.google.speech.logs.AudioStreamDescriptor.Builder, com.google.speech.logs.AudioStreamDescriptorOrBuilder> 
        getDescFieldBuilder() {
      if (descBuilder_ == null) {
        descBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.speech.logs.AudioStreamDescriptor, com.google.speech.logs.AudioStreamDescriptor.Builder, com.google.speech.logs.AudioStreamDescriptorOrBuilder>(
                getDesc(),
                getParentForChildren(),
                isClean());
        desc_ = null;
      }
      return descBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:speech.logs.AudioStream)
  }

  // @@protoc_insertion_point(class_scope:speech.logs.AudioStream)
  private static final com.google.speech.logs.AudioStream DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.speech.logs.AudioStream();
  }

  public static com.google.speech.logs.AudioStream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AudioStream>
      PARSER = new com.google.protobuf.AbstractParser<AudioStream>() {
    @java.lang.Override
    public AudioStream parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AudioStream> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AudioStream> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.speech.logs.AudioStream getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

