// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logs/proto/speech/service/recognizer_log.proto

package com.google.speech.logs;

public interface SpeakerIdMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech.logs.SpeakerIdMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 auth_token_index = 13;</code>
   * @return Whether the authTokenIndex field is set.
   */
  boolean hasAuthTokenIndex();
  /**
   * <code>optional int32 auth_token_index = 13;</code>
   * @return The authTokenIndex.
   */
  int getAuthTokenIndex();

  /**
   * <code>optional float hotword_speaker_id_score = 1;</code>
   * @return Whether the hotwordSpeakerIdScore field is set.
   */
  boolean hasHotwordSpeakerIdScore();
  /**
   * <code>optional float hotword_speaker_id_score = 1;</code>
   * @return The hotwordSpeakerIdScore.
   */
  float getHotwordSpeakerIdScore();

  /**
   * <code>optional float server_speaker_id_score = 4;</code>
   * @return Whether the serverSpeakerIdScore field is set.
   */
  boolean hasServerSpeakerIdScore();
  /**
   * <code>optional float server_speaker_id_score = 4;</code>
   * @return The serverSpeakerIdScore.
   */
  float getServerSpeakerIdScore();

  /**
   * <code>optional float server_text_independent_score = 6;</code>
   * @return Whether the serverTextIndependentScore field is set.
   */
  boolean hasServerTextIndependentScore();
  /**
   * <code>optional float server_text_independent_score = 6;</code>
   * @return The serverTextIndependentScore.
   */
  float getServerTextIndependentScore();

  /**
   * <code>optional float on_device_text_independent_score = 11;</code>
   * @return Whether the onDeviceTextIndependentScore field is set.
   */
  boolean hasOnDeviceTextIndependentScore();
  /**
   * <code>optional float on_device_text_independent_score = 11;</code>
   * @return The onDeviceTextIndependentScore.
   */
  float getOnDeviceTextIndependentScore();

  /**
   * <code>optional bool is_verified = 2 [deprecated = true];</code>
   * @return Whether the isVerified field is set.
   */
  @java.lang.Deprecated boolean hasIsVerified();
  /**
   * <code>optional bool is_verified = 2 [deprecated = true];</code>
   * @return The isVerified.
   */
  @java.lang.Deprecated boolean getIsVerified();

  /**
   * <code>optional bool is_best_speaker = 3;</code>
   * @return Whether the isBestSpeaker field is set.
   */
  boolean hasIsBestSpeaker();
  /**
   * <code>optional bool is_best_speaker = 3;</code>
   * @return The isBestSpeaker.
   */
  boolean getIsBestSpeaker();

  /**
   * <code>repeated .speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel intervals_fired = 5;</code>
   * @return A list containing the intervalsFired.
   */
  java.util.List<com.google.speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel> getIntervalsFiredList();
  /**
   * <code>repeated .speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel intervals_fired = 5;</code>
   * @return The count of intervalsFired.
   */
  int getIntervalsFiredCount();
  /**
   * <code>repeated .speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel intervals_fired = 5;</code>
   * @param index The index of the element to return.
   * @return The intervalsFired at the given index.
   */
  com.google.speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel getIntervalsFired(int index);

  /**
   * <code>repeated .speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel hotword_intervals_fired = 7;</code>
   * @return A list containing the hotwordIntervalsFired.
   */
  java.util.List<com.google.speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel> getHotwordIntervalsFiredList();
  /**
   * <code>repeated .speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel hotword_intervals_fired = 7;</code>
   * @return The count of hotwordIntervalsFired.
   */
  int getHotwordIntervalsFiredCount();
  /**
   * <code>repeated .speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel hotword_intervals_fired = 7;</code>
   * @param index The index of the element to return.
   * @return The hotwordIntervalsFired at the given index.
   */
  com.google.speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel getHotwordIntervalsFired(int index);

  /**
   * <code>repeated .speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel on_device_text_independent_intervals_fired = 12;</code>
   * @return A list containing the onDeviceTextIndependentIntervalsFired.
   */
  java.util.List<com.google.speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel> getOnDeviceTextIndependentIntervalsFiredList();
  /**
   * <code>repeated .speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel on_device_text_independent_intervals_fired = 12;</code>
   * @return The count of onDeviceTextIndependentIntervalsFired.
   */
  int getOnDeviceTextIndependentIntervalsFiredCount();
  /**
   * <code>repeated .speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel on_device_text_independent_intervals_fired = 12;</code>
   * @param index The index of the element to return.
   * @return The onDeviceTextIndependentIntervalsFired at the given index.
   */
  com.google.speech.logs.SpeakerIdMetadata.ConfidenceIntervalLabel getOnDeviceTextIndependentIntervalsFired(int index);

  /**
   * <code>optional bool has_voiceprint = 8;</code>
   * @return Whether the hasVoiceprint field is set.
   */
  boolean hasHasVoiceprint();
  /**
   * <code>optional bool has_voiceprint = 8;</code>
   * @return The hasVoiceprint.
   */
  boolean getHasVoiceprint();

  /**
   * <code>optional float face_id_score = 9;</code>
   * @return Whether the faceIdScore field is set.
   */
  boolean hasFaceIdScore();
  /**
   * <code>optional float face_id_score = 9;</code>
   * @return The faceIdScore.
   */
  float getFaceIdScore();

  /**
   * <code>optional bool is_face_id_selected = 10;</code>
   * @return Whether the isFaceIdSelected field is set.
   */
  boolean hasIsFaceIdSelected();
  /**
   * <code>optional bool is_face_id_selected = 10;</code>
   * @return The isFaceIdSelected.
   */
  boolean getIsFaceIdSelected();
}
